### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by gbryer** [johan-v-r/LibSassBuilder#2]
Would it be possible to add support for Linux?

Thanks

**Comment by johan-v-r** [comment]
Hi @gbryer  - I've updated the tool with the [LibSassHost.Native.linux-x64](https://www.nuget.org/packages/LibSassHost.Native.linux-x64/)

The tool itself works fine on my WSL Ubuntu testing environment, however I was struggling with the NuGet package... Could you perhaps test v1.3.0 and let me know?

**Comment by gbryer** [comment]
Hey

I tested the nuget package. It builds but it doesn't seem to compile the sass files.

**Comment by johan-v-r** [comment]
Okay think I found the issue, please test v1.4

**Comment by gbryer** [comment]
Thanks for sorting that out for me.

This might be a separate issue but when I build the project it compiles the scss file to a css in place but doesn't get picked up to be added to the `MyProject.styles.css` file when using CSS isolation. I have to build to project twice for it to notice that the css file is there or for any changes to be propagated.

**Comment by johan-v-r** [comment]
Sure thing!

Your build issue might be related, however this Lib's build target is set to `PreBuildEvent` so it _should_ finish before the the "main" build.

Also I created this lib because of my build issues described [here](https://github.com/dotnet/aspnetcore/issues/27775) - so this works perfectly with `dotnet watch run` commands.

What are you using to build your app? And what framework is your app?
Perhaps even a repo to replicate would be appreciated.
